# NumPy


In [1]:
import numpy as np

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arrange(10)

# Propiedades de los arrays


In [8]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Copia y vistas de arrays



In [9]:
x = np.arange(10)

In [14]:
z = np.random.random((3,5))
z

array([[0.65171339, 0.80617101, 0.033231  , 0.41769423, 0.11263283],
       [0.80698194, 0.41895189, 0.2369326 , 0.91653787, 0.83154394],
       [0.72379272, 0.57427463, 0.64001175, 0.67467201, 0.73506909]])

#  Algebra lineal con Ptyhon

##  Matrices


In [16]:

row = [1,2,3]
col = [[1],[2],[3]

M = np.array (row,col)
M
       


SyntaxError: invalid syntax (<ipython-input-16-89a773649f3f>, line 4)